/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Area {
  id: string;
  review_cadence: string | null;
  review_cadence_vocab: Generated<string>;
  /**
   * What "maintained" means for this area. Required because an area without a standard is just a folder name.
   */
  standard: string;
  status: string;
  status_vocab: Generated<string>;
  type: Generated<string>;
}

export interface Document {
  amount: Numeric | null;
  amount_currency: string | null;
  case: string | null;
  court: string | null;
  coverage_end: Timestamp | null;
  coverage_start: Timestamp | null;
  doc_date: Timestamp;
  doc_type: string;
  doc_type_vocab: Generated<string>;
  expires: Timestamp | null;
  file: string;
  filed_on: Timestamp | null;
  gross: Numeric | null;
  gross_currency: string | null;
  id: string;
  jurisdiction: string | null;
  license_key: string | null;
  net: Numeric | null;
  net_currency: string | null;
  odometer: Numeric | null;
  pay_period: string | null;
  period: string | null;
  policy_number: string | null;
  product: string | null;
  rating: string | null;
  rent: Numeric | null;
  rent_currency: string | null;
  revision: string | null;
  seats: Numeric | null;
  status: string | null;
  status_vocab: Generated<string>;
  target: string | null;
  tax_year: Numeric | null;
  term_end: Timestamp | null;
  term_start: Timestamp | null;
  type: Generated<string>;
  valid_until: Timestamp | null;
}

export interface Group {
  id: string;
  purpose: string | null;
  type: Generated<string>;
}

export interface Journal {
  date: Timestamp;
  id: string;
  period: string;
  period_vocab: Generated<string>;
  type: Generated<string>;
  week_end: Timestamp | null;
  week_start: Timestamp | null;
}

export interface Link {
  field: string;
  source: string;
  source_type: string;
  target: string;
  target_type: string;
}

export interface LinkField {
  field: string;
  inverse: string;
  multi: boolean;
  source_type: string;
  source_vocab: Generated<string>;
  target_type: string;
  target_vocab: Generated<string>;
}

export interface Meeting {
  agenda: string | null;
  date: Timestamp;
  id: string;
  result: string | null;
  type: Generated<string>;
}

export interface Note {
  id: string;
  note_type: string;
  note_type_vocab: Generated<string>;
  type: Generated<string>;
}

export interface Organization {
  id: string;
  industry: string | null;
  org_type: string | null;
  org_type_vocab: Generated<string>;
  type: Generated<string>;
  website: string | null;
}

export interface Person {
  email: string[] | null;
  id: string;
  met: Timestamp | null;
  organization_text: string | null;
  phone: string[] | null;
  role: string | null;
  type: Generated<string>;
}

export interface PersonRelationship {
  person: string;
  value: string;
  value_vocab: Generated<string>;
}

export interface Project {
  end: Timestamp | null;
  id: string;
  result: string | null;
  scope: string;
  scope_vocab: Generated<string>;
  start: Timestamp | null;
  status: string;
  status_vocab: Generated<string>;
  type: Generated<string>;
}

export interface Record {
  /**
   * Null means live. Deliberately separate from any type's status: archiving is about location and attention, status is domain state.
   */
  archived_on: Timestamp | null;
  /**
   * Everything below the frontmatter. Never parsed for data; an empty body is valid.
   */
  body: Generated<string>;
  created: Generated<Timestamp>;
  id: string;
  tags: Generated<string[]>;
  title: string | null;
  type: string;
  type_vocab: Generated<string>;
  updated: Timestamp | null;
}

export interface Resource {
  id: string;
  resource_type: string;
  resource_type_vocab: Generated<string>;
  source: string | null;
  topic: string[] | null;
  type: Generated<string>;
  url: string | null;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  duration_ms: number;
  name: string;
  version: number;
}

export interface System {
  id: string;
  system_type: string;
  system_type_vocab: Generated<string>;
  type: Generated<string>;
}

export interface Task {
  /**
   * Stamped on the transition into done. Without it "what did I finish last week" is unanswerable, since updated moves on every edit.
   */
  completed: Timestamp | null;
  due: Timestamp | null;
  id: string;
  priority: string | null;
  priority_vocab: Generated<string>;
  scheduled: Timestamp | null;
  state: string;
  state_vocab: Generated<string>;
  type: Generated<string>;
}

export interface Vocabulary {
  name: string;
  value: string;
}

export interface World {
  id: string;
  setting: string | null;
  status: string;
  status_vocab: Generated<string>;
  type: Generated<string>;
}

export interface WorldEntry {
  entry_type: string;
  entry_type_vocab: Generated<string>;
  id: string;
  type: Generated<string>;
}

export interface DB {
  area: Area;
  document: Document;
  group: Group;
  journal: Journal;
  link: Link;
  link_field: LinkField;
  meeting: Meeting;
  note: Note;
  organization: Organization;
  person: Person;
  person_relationship: PersonRelationship;
  project: Project;
  record: Record;
  resource: Resource;
  schema_migrations: SchemaMigrations;
  system: System;
  task: Task;
  vocabulary: Vocabulary;
  world: World;
  world_entry: WorldEntry;
}
